name: GitHub Actions Secrets
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secrets
        env: 
          MY_SECRET: ${{ secrets.liz-secret-host}}
        run: echo "My secret is ${MY_SECRET}"
        